ens_sylvain_davenel:
    resource: "@EnsSylvainDavenelBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

EnsSylvainDavenelBundle_homepage:
    pattern:  /
    defaults: { _controller: EnsSylvainDavenelBundle:job:index }